version: "3.0"

services:
  database_upfine:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: upfine
    ports:
      - "5432:5432"
    volumes:
      - database_upfine_data:/var/lib/postgresql/data
    networks:
      - upfine-network

volumes:
  database_upfine_data:

networks:
  upfine-network:
    driver: bridge