DROP TABLE IF EXISTS "tb_corporation" CASCADE;
CREATE TABLE "tb_corporation" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "cnpj" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_corporation_UNIQUE" ON "tb_corporation" ("id" ASC);

DROP TABLE IF EXISTS "tb_market_data" CASCADE;
CREATE TABLE "tb_market_data" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "corporation_id" INT8 NOT NULL,
  "price" DECIMAL NOT NULL,
  "pl" DECIMAL NOT NULL,
  "pvp" DECIMAL NOT NULL,
  "div_yield" DECIMAL NOT NULL,
  "lpa" DECIMAL NOT NULL,
  "vpa" DECIMAL NOT NULL,
  "net_margin" DECIMAL NOT NULL,
  "roe" DECIMAL NOT NULL,
  "last_reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_market_data_tb_corporation" FOREIGN KEY ("corporation_id") REFERENCES "tb_corporation" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_market_data_UNIQUE" ON "tb_market_data" ("id" ASC);
CREATE INDEX "fk_tb_market_data_tb_corporation_idx" ON "tb_market_data" ("corporation_id" ASC);

DROP TABLE IF EXISTS "tb_ipe" CASCADE;
CREATE TABLE "tb_ipe" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "corporation_id" INT8 NOT NULL,
  "subject" TEXT NOT NULL,
  "link" TEXT NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_ipe_tb_corporation" FOREIGN KEY ("corporation_id") REFERENCES "tb_corporation" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_ipe_UNIQUE" ON "tb_ipe" ("id" ASC);
CREATE INDEX "fk_tb_ipe_tb_corporation_idx" ON "tb_ipe" ("corporation_id" ASC);


DROP TABLE IF EXISTS "tb_relevant_fact" CASCADE;
CREATE TABLE "tb_relevant_fact" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "ipe_id" INT8 NOT NULL,
  "summarized_text" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_relevant_fact_tb_ipe" FOREIGN KEY ("ipe_id") REFERENCES "tb_ipe" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_relevant_fact_UNIQUE" ON "tb_relevant_fact" ("id" ASC);
CREATE INDEX "fk_tb_relevant_fact_tb_ipe_idx" ON "tb_relevant_fact" ("ipe_id" ASC);


DROP TABLE IF EXISTS "tb_email" CASCADE;
CREATE TABLE "tb_email" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(255) NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE(email)
);
CREATE UNIQUE INDEX "id_email_UNIQUE" ON "tb_email" ("id" ASC);
